# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basesocialaccount',
            name='name',
            field=models.CharField(default='', max_length=128, verbose_name='Account name'),
            preserve_default=False,
        ),
    ]
