# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_auto_20160306_1613'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=set([('feed', 'guid')]),
        ),
    ]
