# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_entry_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='title',
            field=models.CharField(default='', max_length=256, verbose_name='Feed title'),
            preserve_default=False,
        ),
    ]
